PROCESS TOOK 10 SECONDS ERROR in  benchmark_DiCE.py  AND DSNAME  8 FOR C 0 AND ROW 1
PROCESS TOOK 15 SECONDS ERROR in  benchmark_DiCE.py  AND DSNAME  8 FOR C 0 AND ROW 0
