PROCESS TOOK 900 SECONDS ERROR in  benchmark_GROWINGSPHERES3.py  AND DSNAME  20 FOR C 0 AND ROW 0
PROCESS TOOK 900 SECONDS ERROR in  benchmark_GROWINGSPHERES3.py  AND DSNAME  20 FOR C 0 AND ROW 1
