PROCESS TOOK 2296 SECONDS SUCCESS in  benchmark_MACE.py  AND DSNAME  7
PROCESS TOOK 2400 SECONDS ERROR in  benchmark_MACE.py  AND DSNAME  7 FOR C 0 AND ROW 1
